version: "3.7"

services:
  backend:
    build:
      context: ./
    ports:
<<<<<<< HEAD
      - 5000:5000
=======
    - 5000:5000
>>>>>>> 2814e6c7fe40e5c437d06a3d30b3ff1637942795
    volumes:
      - "backend_uploads:/app/uploads"

volumes:
  backend_uploads:
